/Functional Programming in Scala for Mortals/ is a book aimed at Scala
developers with an Object Oriented background who wish to learn the
*Functional Programming* paradigm.

This book is for sale at http://leanpub.com/fp-scala-mortals

* Why?

Scala is missing a comprehensive and practical introduction to FP. We
do not believe that learning Haskell should be a prerequisite. We also
do not accept that the merits of FP are obvious. Therefore, this book
justifies every concept with practical examples, in Scala.

* Call for Action

If FP is going to become more than a niche within the Scala community,
it needs to be easy to learn and use by the typical OOP developer.

If you are trying to learn FP, you can help out by contributing
feedback of what helped you as you progress in your journey, and by
reading early drafts of this book.

If you are an expert in FP, you can help out by assisting the author
in his journey to understand, e.g. answering questions in
[[https://github.com/fommil/drone-dynamic-agents/issues?q=is%3Aissue+is%3Aopen+label%3A%22needs+guru%22][drone-dynamic-agents]].
